---
id: 201677
name: SaaSEvgMSSQL2Snow INSERT
description: ''
user:
  id: 3979
  email: ask_salesforce@mz.co.kr
transfer_option:
  transfer_type: normal
  in:
    type: sqlserver
    sqlserver_connection:
      id: 189
      name: SaaSEvgMSSQL-RDS
    database: SalesforceCopy
    schema: dbo
    default_timezone: UTC
    column_options: 
    table: test_nrt
    incremental_columns:
    - id
    fetch_rows: 10000
    connect_timeout: 300
    socket_timeout: 1800
    custom_variables: []
    incremental_loading_enabled: true
  out:
    type: snowflake
    snowflake_connection:
      id: 380
      name: SaaSEvgVO45173
    warehouse: MZC_SAMPLE_WAREHOUSE
    database: TROCCO
    schema: PUBLIC
    table: sqlserver2
    retry_limit: 12
    retry_wait: 1000
    max_retry_wait: 1800000
    mode: insert
    default_timezone: UTC
    column_options: 
    empty_field_as_null: true
    batch_size: 200
    delete_stage_on_error: false
    custom_variables: []
  data_settings:
    columns:
    - name: id
      src: id
      default: ''
      type: long
    - name: BRN
      src: BRN
      default: ''
      type: string
  is_runnable_concurrently: true
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
